[package]
name = "typeck"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../diagnostics" }
source = { path = "../source" }
hir = { path = "../hir" }
salsa = "0.16.0"
itertools = "0.10.0"
