[package]
name = "docs"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
hir = { path = "../hir" }
rustc-hash = "1.1.0"
html-builder = "0.2.0"
relative-path = "1.3.2"
