[workspace]
members = [
    "compiler/shadow",
    "compiler/driver",
    "compiler/source",
    "compiler/syntax",
    # "compiler/hir",
    # "compiler/check",
    # "compiler/mir",
    # "compiler/codegen",
]
