[workspace]
members = [
  "compiler/hir",
  "compiler/parser",
  "compiler/syntax",
  "compiler/base_db",
  "compiler/diagnostics",
  "compiler/paths",
  "compiler/vfs",
  "compiler/driver",
  "compiler/fi",
]
