[workspace]
members = [
    "compiler/shadow",
    "compiler/driver",
    "compiler/data_structures",
    "compiler/diagnostics",
    "compiler/source",
    "compiler/syntax",
    "compiler/hir",
    "compiler/check",
    "compiler/mir",
    # "compiler/codegen",
]
