[package]
name = "hir"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../../../.crates/diagnostics" }
syntax = { path = "../syntax" }
seahash = "4.0.0"
derivative = "2.1.1"
serde = { version = "1.0.116", features = ["derive"] }
