[package]
name = "hir"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../diagnostics" }
data_structures = { path = "../data_structures" }
source = { path = "../source" }
syntax = { path = "../syntax" }
codespan = "0.9.5"
codespan-reporting = "0.9.5"
salsa = "0.16.0"
serde = { version = "^1.0.117", features = ["derive"] }
bincode = "1.3.1"
