[package]
name = "driver"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../diagnostics" }
source = { path = "../source" }
syntax = { path = "../syntax" }
hir = { path = "../hir" }
typeck = { path = "../typeck" }
lower = { path = "../lower" }
linker = { path = "../linker" }
backend = { path = "../backend" }
salsa = "^0.16.0"
serde = { version = "^1.0.117", features = ["derive"] }
bincode = "1.3.1"
relative-path = "1.3.2"
