[package]
name = "driver"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../diagnostics" }
source = { path = "../source" }
syntax = { path = "../syntax" }
hir = { path = "../hir" }
check = { path = "../check" }
layout = { path = "../layout" }
mir = { path = "../mir" }
salsa = "^0.16.0"
