[package]
name = "driver"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2021"

[dependencies]
diagnostics = { path = "../diagnostics" }
codegen = { path = "../codegen" }
metadata = { path = "../metadata" }
hir = { path = "../hir" }
hir_def = { path = "../hir_def" }
syntax = { path = "../syntax" }
base_db = { path = "../base_db" }
paths = { path = "../paths" }
vfs = { path = "../vfs" }
cfg = { path = "../cfg" }
project = { path = "../project" }
salsa = "0.16.0"
ariadne = { git = "https://github.com/Cyberduc-k/ariadne.git" }
serde = { version = "^1.0.123", features = ["derive"] }
toml = "0.5.8"
anyhow = "1.0.38"
target-lexicon = "0.12.0"
rustc-hash = "1.1.0"
path-slash = "0.1.4"
libloading = "0.7.0"
tracing = "^0.1"
