[package]
name = "driver"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../diagnostics" }
docs = { path = "../docs" }
codegen = { path = "../codegen" }
mir = { path = "../mir" }
hir = { path = "../hir" }
hir_def = { path = "../hir_def" }
base_db = { path = "../base_db" }
syntax = { path = "../syntax" }
salsa = "0.16.0"
annotate-snippets = { version = "0.9.0", features = ["color"] }
serde = { version = "1.0.123", features = ["derive"] }
toml = "0.5.8"
anyhow = "1.0.38"
relative-path = "1.3.2"
path-slash = "0.1.4"
libloading = "0.7.0"
