[package]
name = "base_db"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2021"

[dependencies]
syntax = { path = "../syntax" }
salsa = "0.16.0"
smol_str = "0.1.17"
rustc-hash = "1.1.0"
relative-path = { version = "1.7.2", features = ["serde"] }
