[package]
name = "base_db"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
syntax = { path = "../syntax" }
salsa = "0.16.0"
rustc-hash = "1.1.0"
relative-path = "1.3.2"
serde = { version = "^1.0.123", features = ["derive"] }
bincode = "^1.3.3"
