[package]
name = "mir"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
hir = { path = "../hir" }
base_db = { path = "../base_db" }
target-lexicon = "0.12.0"
rustc-hash = "1.1.0"
salsa = "0.16.0"
