[package]
name = "lower"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
hir = { path = "../hir" }
check = { path = "../check" }
lowlang = { path = "../../../lowlang/umbrella" }
salsa = "0.16.0"
mangling = "^0.2.2"
