[package]
name = "paths"
version = "0.1.0"
edition = "2021"

[dependencies]
path-absolutize = { version = "3.0.14", features = ["once_cell_cache"] }
serde = { version = "^1.0.123", features = ["derive"] }
