[package]
name = "shadow"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
driver = { path = "../driver" }
base_db = { path = "../base_db" }
repl = { path = "repl" }
clap = "2.33.3"
