[package]
name = "shadow"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
driver = { path = "../driver" }
source = { path = "../source" }
clap = "2.33.3"
toml = "^0.5.7"
