[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
backend_llvm = { path = "../backend_llvm" }
backend_js = { path = "../backend_js" }
mir = { path = "../mir" }
hir = { path = "../hir" }
base_db = { path = "../base_db" }
project = { path = "../project" }
paths = { path = "../paths" }
# lld_rs = "140.0.0"
cc = "^1.0.78"
mangling = "^0.2.3"
tracing = "^0.1"
tempfile = "3.2.0"
salsa = "0.17.0-pre.2"
target-lexicon = { version = "0.12.0", features = ["std"] }
