[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
mir = { path = "../mir" }
hir = { path = "../hir" }
base_db = { path = "../base_db" }
project = { path = "../project" }
paths = { path = "../paths" }
target-lexicon = { version = "0.12.0", features = ["std"] }
libloading = "0.7.0"
tempfile = "3.2.0"
salsa = "0.17.0-pre.2"
tracing = "^0.1"

[dependencies.tracing-subscriber]
version = "0.3.15"
default-features = false
features = ["env-filter", "smallvec", "fmt", "ansi"]
