[package]
name = "codegen"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
source = { path = "../source" }
check = { path = "../check" }
layout = { path = "../layout" }
mir = { path = "../mir" }
inkwell = "0.1.0-llvm10sample"
salsa = "^0.16.0"
by_address = "1.0.4"
tempfile = "3.1.0"
anyhow = "1.0.34"
