[package]
name = "codegen"
version = "0.1.0"
edition = "2018"

[dependencies]
mir = { path = "../mir" }
hir = { path = "../hir" }
base_db = { path = "../base_db" }
cranelift = "0.74.0"
cranelift-module = "0.74.0"
cranelift-object = "0.74.0"
# cranelift-jit = "0.74.0"
target-lexicon = "0.12.0"
tempfile = "3.2.0"
salsa = "0.16.0"
