[package]
name = "codegen"
version = "0.1.0"
edition = "2018"

[dependencies]
lower = { path = "../lower" }
hir = { path = "../hir" }
base_db = { path = "../base_db" }
target-lexicon = "0.12.0"
tempfile = "3.2.0"
salsa = "0.16.0"
