[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
hir = { path = "../hir" }
base_db = { path = "../base_db" }
project = { path = "../project" }
paths = { path = "../paths" }
target-lexicon = "0.12.0"
libloading = "0.7.0"
tempfile = "3.2.0"
salsa = "0.16.0"
tracing = "^0.1"

[dependencies.tracing-subscriber]
version = "0.3.15"
default-features = false
features = ["env-filter", "smallvec", "fmt", "ansi"]
