[package]
name = "codegen"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
source = { path = "../source" }
check = { path = "../check" }
layout = { path = "../layout" }
mir = { path = "../mir" }
linker = { path = "../linker" }
inkwell = "0.1.0-llvm10sample"
target-lexicon = "^0.11.0"
salsa = "^0.16.0"
by_address = "1.0.4"
tempfile = "3.1.0"
anyhow = "1.0.34"
libloading = "^0.6.5"
