[package]
name = "mir"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
hir = { path = "../hir" }
check = { path = "../check" }
layout = { path = "../layout" }
index_vec = "0.1.2"
salsa = "0.16.0"
