[package]
name = "language-server"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "^0.6"
lsp-types = "^0.93"
serde_json = "^1.0"
crossbeam-channel = "^0.5.4"
threadpool = "^1.8"
anyhow = "1.0.38"
tracing = "^0.1"
