[package]
name = "shadow"
version = "0.1.0"
description = "shade programming language compiler"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
driver = { path = "../driver" }
target-lexicon = "^0.10.0"
clap = "2.33.3"
